# Generated by Django 4.2.6 on 2023-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginners_class',
            name='tutor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
