# Generated by Django 4.2.6 on 2023-10-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0004_customerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
