# Generated by Django 4.2.6 on 2023-10-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='balance',
        ),
    ]
