# Generated by Django 4.2.6 on 2023-10-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_userwallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
